builders:
  - script
upstream:
  - eduid-userdb
  - eduid-common
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
script:
  - "echo $(docker inspect -f '{{.NetworkSettings.Gateway}}' $(hostname)) localhost >> /etc/hosts"
  - "virtualenv venv"
  - ". venv/bin/activate"
  - "pip install -U setuptools"
  - "pip install --index-url https://pypi.sunet.se -r requirements/testing.txt"
  - "nosetests"
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se
