builders:
  - script
upstream:
  - eduid-userdb
  - eduid-common
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
script:
  - virtualenv venv
  - . venv/bin/activate
  - pip install -U setuptools
  - pip install --index-url https://pypi.sunet.se -r requirements/testing.txt
  - nosetests
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se
