builders:
  - script
upstream:
  - eduid-userdb
  - eduid-common
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U setuptools wheel"
  - "pip install --index-url https://pypi.sunet.se -r requirements/testing.txt"
  - "nosetests"
  - "mypy --ignore-missing-imports src/eduid_action"
  - "python setup.py sdist bdist_wheel --universal"
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se
