builders:
  - python
upstream:
  - eduid-userdb
  - eduid-common
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: eduid_action
clean_workspace: true

extra_jobs:
  - name: eduid-action-docker
    builders:
      - docker
    docker_name: eduid/eduid-action
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-pythonenv
      - eduid-action
