sudo: required
addons:
  apt:
    packages:
      xmlsec1  # pysaml2 needs to find an xmlsec1 binary
language: python
python:
  - "2.7"
before_install:
  - docker pull docker.sunet.se/eduid/redis:latest
  - docker pull docker.sunet.se/library/etcd:v2.2.5
  - docker pull docker.sunet.se/eduid/mongodb:latest
services:
  - docker
# command to install dependencies
install:
  - pip install -U setuptools
  - pip install --index-url https://pypi.sunet.se -r requirements/testing.txt
  - cp /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/eduid_webapp/actions/templates /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/eduid_webapp/
# command to run tests
script:
  - pip freeze
  - nosetests
